version: '3'

tasks:
  CI:
    deps:
      - test
      - check

  test:
    deps:
      - test:doc
      - test:lib

  check:
    deps:
      - check:lib

  ##### test #####
  test:doc:
    cmds:
      - cargo test --doc

  test:lib:
    cmds:
      - cargo test --lib --no-default-features
      - cargo test --lib --features alloc
  
  ##### check #####
  check:lib:
    cmds:
      - cargo check --no-default-features
      - cargo check --features alloc
